### ISSUE TITLE
Diseño en Mockup.

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/Remi3.0#15]
Diseñar una interfaz gráfica que muestre un prototipo de como se verá la DApp.

**Comment by Lizzetee** [comment]
Diseño final del mockup

![Image](https://user-images.githubusercontent.com/105515979/204362238-1f022505-bddd-4e42-a84d-d35520e4d997.png)



![Image](https://user-images.githubusercontent.com/105515979/204362311-106e54c8-4f47-400d-a6fc-e8b0829c3b7f.png)



![Image](https://user-images.githubusercontent.com/105515979/204362408-a34a3495-5b2a-4180-a79a-490a1ebef210.png)



![Image](https://user-images.githubusercontent.com/105515979/204362484-c9c4bc28-e095-42ce-83a5-0c7cd855eaa5.png)



![Image](https://user-images.githubusercontent.com/105515979/204362572-ca4b0a26-b48d-43df-87e2-fa6812c821f0.png)



![Image](https://user-images.githubusercontent.com/105515979/204362647-9432bb33-924e-4fc5-bd56-fef874e114ec.png)
